version: '3.5'

services:
    api:
        build: .
        volumes:
            - ./:/app
        working_dir: /app
        #environment:
            #- FLASK_APP=app.py
            #- FLASK_DEBUG=1
        #command: flask run --host=0.0.0.0
        entrypoint: /bin/ash
        stdin_open: true
        tty: true
#FLASK_APP=app.py FLASK_DEBUG=1 python -m flask run --host=0.0.0.0 --port=8000
        extra_hosts:
            - "host.docker.internal:192.168.0.3"

    webserver:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        extra_hosts:
            - "host.docker.internal:192.168.0.3"
                                    
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodata:/data/db
        extra_hosts:
            - "host.docker.internal:192.168.0.3"        

volumes:
    mongodata: